name: native_download_plugin
description: Flutter Native Download Plugin Project
homepage: https://github.com/tylanyildiz/native_download_plugin
version: 0.1.8

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.videntium.native_download_plugin
        pluginClass: NativeDownloadPlugin
      ios:
        pluginClass: NativeDownloadPlugin